// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhBk31DVQe-g4O1hetyh1HFHnJWdzI3nA',
    appId: '1:79247422623:web:5498779e260fd293ff1eaa',
    messagingSenderId: '79247422623',
    projectId: 'enviroguard-1',
    authDomain: 'enviroguard-1.firebaseapp.com',
    storageBucket: 'enviroguard-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoWKSJypRupxXKBSIYA0O-lzHz1yyc2ZI',
    appId: '1:79247422623:android:58d247cc86ebf7c0ff1eaa',
    messagingSenderId: '79247422623',
    projectId: 'enviroguard-1',
    storageBucket: 'enviroguard-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_rAe7ltCUkQ-GeUzzfxYlnA1KRX513L4',
    appId: '1:79247422623:ios:8e5715f6bcd321d9ff1eaa',
    messagingSenderId: '79247422623',
    projectId: 'enviroguard-1',
    storageBucket: 'enviroguard-1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_rAe7ltCUkQ-GeUzzfxYlnA1KRX513L4',
    appId: '1:79247422623:ios:8e5715f6bcd321d9ff1eaa',
    messagingSenderId: '79247422623',
    projectId: 'enviroguard-1',
    storageBucket: 'enviroguard-1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhBk31DVQe-g4O1hetyh1HFHnJWdzI3nA',
    appId: '1:79247422623:web:289b0d0f6bafde14ff1eaa',
    messagingSenderId: '79247422623',
    projectId: 'enviroguard-1',
    authDomain: 'enviroguard-1.firebaseapp.com',
    storageBucket: 'enviroguard-1.firebasestorage.app',
  );
}
